Zadanie 1
Napisać funkcję, która:
• Przyjmie na wejście tensor o dowolnym kształcie typu tf.float32.
• Przemnoży go o samego siebie element po elemencie
• Odejmie macierz złożoną z samych jedynek o tym samym rozmiarze
• Wyzeruje wszystkie wartości powyżej 2
• Wypłaszczy wynikową macierz do wektora i ją zwróci
Funkcję wywołać dla trzech tensorów powstałych przez użycie operacji tf.random.uniform() z
wartościami z zakresu 0-10 przy argumentach „shape”:
- [5]
- [10, 5]
- [5, 7, 9]
Należy wykorzystać operacje: tf.random.uniform, tf.ones_like, tf.where, tf.reshape.

In [2]:
import tensorflow as tf

def zad1(T):
    assert T.dtype == tf.float32
    T = T*T
    ones_tensor = tf.ones_like(T, dtype=tf.float32)
    T = tf.subtract(T, ones_tensor)
    T = tf.where(T > 2, 0, T)
    T = tf.reshape(T, [-1])
    return T

tensor1 = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.float32)
tensor2 = tf.random.uniform(shape=[10, 5], minval=0, maxval=10, dtype=tf.float32)
tensor3 = tf.random.uniform(shape=[5, 7, 9], minval=0, maxval=10, dtype=tf.float32)

print("Wynik dla tensora o kształcie [5]:", zad1(tensor1))
print("Wynik dla tensora o kształcie [10, 5]:", zad1(tensor2))
print("Wynik dla tensora o kształcie [5, 7, 9]:", zad1(tensor3))


Wynik dla tensora o kształcie [5]: tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
Wynik dla tensora o kształcie [10, 5]: tf.Tensor(
[ 0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        -0.2079724
  0.         0.         0.         0.         0.         1.3590169
 -0.9900617  0.         0.         0.         0.         0.
  0.         0.         0.         0.        -0.2814558  0.
  0.         0.         0.         0.         0.        -0.4986422
  0.         0.       ], shape=(50,), dtype=float32)
Wynik dla tensora o kształcie [5, 7, 9]: tf.Tensor(
[ 0.          0.          0.          0.         -0.13269597  0.
  0.6156771   0.          0.          0.          0.          0.
  0.         -0.60803723  0.         -0.7865039   0.          0.
  0.          0.          0.         -0.48273194  0.       

Zadanie 2
Napisać funkcję, która:
• Przyjmie na wejście tensor 4x3 (zabezpieczyć się przed złymi wymiarami np. poprzez
assert(...))
• Przekształci ten tensor w tensor 6x2
• Dorobi do niego dodatkowy wymiar w osi zerowej i powieli wszystkie wartości wzdłuż
tej osi 5 razy
• Doda do niej macierz z losowymi wartościami z zakresu 0-10 o tym samym kształcie
(nie należy hardkodować wymiarów)
• Przytnie wartości poniżej 3 i powyżej 5, po czym zwróci wynikowy tensor
Funkcję należy wywołać dla tensora typu tf.int32:
[[1, 2 , 3, ], [2, 3, 4], [4, 5, 6], [5, 6, 7]]
Należy wykorzystać operacje: tf.constant, tf.shape, tf.reshape, tf.expand_dims, tf.tile,
tf.random.uniform, tf.clip_by_value


In [9]:
def zad2(T):
  assert all(tf.shape(T) == [4, 3])
  T=tf.reshape(T,[6,2])
  T=tf.expand_dims(T,0)
  T=tf.tile(T,[5,1,1])
  T=T+tf.random.uniform(shape=tf.shape(T), minval=0, maxval=10,dtype=tf.int32)
  T=tf.clip_by_value(T,3,5)
  return T

Z2=tf.constant([[1, 2 , 3 ], [2, 3, 4], [4, 5, 6], [5, 6, 7]], tf.int32)
zad2(Z2)

<tf.Tensor: shape=(5, 6, 2), dtype=int32, numpy=
array([[[5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[3, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[3, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[3, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [3, 4],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]]], dtype=int32)>

Zadanie 3
Napisać funkcję, która:
• Przyjmie na wejście dwa tensory o identycznym kształcie (zabezpieczyć się przed
niezgodnymi kształtami)
• Wygeneruje tensor indeksów wszystkich wartości równych 2 w tensorze pierwszym
• Na podstawie tensora indeksów wygeneruje wektor ze wszystkimi wartościami
odpowiadającymi tym indeksom w tensorze drugim
• Obliczy średnią wartość z wynikowego wektora i przemnoży ją o tensor pierwszy
• Dokona konkatenacji tensora pierwszego po przemnożeniu i drugiego wzdłuż osi
zerowej
• Zredukuje wartości wzdłuż osi zerowej do wartości maksymalnej i zwróci wynikowy
tensor
Funkcję należy wywołać dla dwóch tensorów typu tf.float32:
[[1, 2, 3], [4, 3, 2], [5, 2, 3]] i [[78, 43, 23], [45, 77, 32], [99, 88, 77]]
Należy wykorzystać operacje: tf.constant, tf.shape, tf.where, tf.gather/tf.gather_nd,
tf.math.reduce_mean, tf.concat, tf.math.reduce_max

In [13]:
def zad3(T1,T2):
  assert all(tf.shape(T1) == tf.shape(T1))
  TI=tf.where(T1==2)
  V=tf.gather_nd(T2,TI)
  avg=tf.math.reduce_mean(V)*T1
  T=tf.concat([avg,T2],0)
  return tf.math.reduce_max(T,0)

T1=tf.constant([[1, 2, 3], [4, 3, 2], [5, 2, 3]], tf.float32)
T2=tf.constant([[78, 43, 23], [45, 77, 32], [99, 88, 77]], tf.float32)
zad3(T1,T2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([271.66666, 163.     , 163.     ], dtype=float32)>