# Podstawy głębokich sieci neuronowych
### Lab 2
Paweł Marczewski, 148099

In [1]:
import tensorflow as tf

## Zadanie 1

Napisać funkcję, która:
- Przyjmie na wejście tensor o dowolnym kształcie typu `tf.float32`.
- Utworzy maskę według warunku _x > 0_
- Na podstawie maski utworzy wektor elementów z tensora wejściowego
- Przeprowadzi mnożenie algebraiczne wynikowego wektora o siebie, ale z
transpozycją drugiego czynnika.
- Dorobi dodatkowy wymiar w osi 0 i powtórzy tensor 5 razy wzdłuż tej osi
- Zwróci wynik

Funkcję wywołać dla trzech tensorów powstałych przez użycie operacji `tf.random.uniform()` z
wartościami z zakresu _<-10,10>_ przy argumentach _shape_:
- `[3]`
- `[33, 7]`
- `[2, 32, 6]`

**Należy wykorzystać operacje**: [`tf.boolean_mask`](https://www.tensorflow.org/api_docs/python/tf/boolean_mask), [`tf.transpose`](https://www.tensorflow.org/api_docs/python/tf/transpose), [`tf.linalg.matmul`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul), [`tf.expand_dims`](https://www.tensorflow.org/api_docs/python/tf/expand_dims), [`tf.repeat`](https://www.tensorflow.org/api_docs/python/tf/repeat)

In [2]:
def zad1(T)->tf.Tensor:
    assert T.dtype == tf.float32
    mask = T > 0
    vec = tf.boolean_mask(T,mask)
    vec=vec[tf.newaxis]
    vec=tf.linalg.matmul(vec,tf.transpose(vec))
    vec=tf.expand_dims(vec,0)
    vec=tf.repeat(vec,5,axis=0)
    return vec

T1=tf.random.uniform([3],-10,10)
T2=tf.random.uniform([33,7],-10,10)
T3=tf.random.uniform([2,32,6],-10,10)
print(zad1(T1))
print(zad1(T2))
print(zad1(T3))

tf.Tensor(
[[[99.46262]]

 [[99.46262]]

 [[99.46262]]

 [[99.46262]]

 [[99.46262]]], shape=(5, 1, 1), dtype=float32)
tf.Tensor(
[[[3108.901]]

 [[3108.901]]

 [[3108.901]]

 [[3108.901]]

 [[3108.901]]], shape=(5, 1, 1), dtype=float32)
tf.Tensor(
[[[6160.5493]]

 [[6160.5493]]

 [[6160.5493]]

 [[6160.5493]]

 [[6160.5493]]], shape=(5, 1, 1), dtype=float32)


## Zadanie 2
Napisać funkcję, która:
- Przyjmie na wejście tensor o dowolnym kształcie typu `tf.float32`.
- Sprawdzi, czy wartość minimalna w tensorze jest większa od zera. Jeśli jest, to wytnie pierwszą kolumnę tensora, a jeśli nie to drugą (za pomocą slicingu).
- Podzieli wynikowy tensor przez 8
- Zaokrągli wartości w tensorze do najbliższych liczb całkowitych
- Zmieni typ tensora na `tf.int32` i zwróci go

Funkcję wywołać dla tensorów:
- `[[5, 6], [7, 3], [4, 5]]`
- `[[-4, 5, 6], [7, 8, 9]]`

**Należy wykorzystać operacje**: [`tf.constant`](https://www.tensorflow.org/api_docs/python/tf/constant), [`tf.math.reduce_min`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min), [`tf.where`](https://www.tensorflow.org/api_docs/python/tf/where), [`tf.math.round`](https://www.tensorflow.org/api_docs/python/tf/math/round), [`tf.cast`](https://www.tensorflow.org/api_docs/python/tf/cast)

In [9]:
def zad2(T)->tf.Tensor:
    assert T.dtype == tf.float32
    minval = tf.math.reduce_min(T)
    print(T)
    if(minval>0):
        T=T[:,1:]
    else:
        T=tf.concat([T[:,:1],T[:,2:]],1) # wytnij drugą kolumnę
    print(T)
    T=T/8
    T=tf.math.round(T)
    T=tf.cast(T, dtype=tf.int32)
    return T
T1=tf.constant([[5, 6], [7, 3], [4, 5]],dtype=tf.float32)
T2=tf.constant([[-4, 5, 6], [7, 8, 9]],dtype=tf.float32)
print(zad2(T1))
print(zad2(T2))

tf.Tensor(
[[5. 6.]
 [7. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[6.]
 [3.]
 [5.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[1]
 [0]
 [1]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[-4.  5.  6.]
 [ 7.  8.  9.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-4.  6.]
 [ 7.  9.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0 1]
 [1 1]], shape=(2, 2), dtype=int32)


## Zadanie 3

Napisać funkcję, która:
- Przyjmie na wejście tensory o dowolnych, ale identycznych kształtach typu `tf.float32` (należy zabezpieczyć się przed odmiennymi kształtami przez asercję).
- Utworzy tensor indeksów elementów większych od 0 i mniejszych od 4 dla tensora
pierwszego.
- Na podstawie tego tensora indeksów podmieni odpowiadające wartości w tensorze
drugim na wartość 7.
- Zwróci zmodyfikowany tensor

Funkcję wywołać dla tensorów:
- `x1 = [[8, 9, 0], [2, 3, 4], [6, 1, 8]]` i `x2 = [[4, 5, 8], [23, 32, 14], [6, 1, 15]]`
- `x1 = [[8, 9], [3, 4], [6, 2]]` i `x2 = [[5, 8], [23, 14], [6, 1]]`

**Należy wykorzystać operacje**: [`tf.constant`](https://www.tensorflow.org/api_docs/python/tf/constant), [`tf.shape`](https://www.tensorflow.org/api_docs/python/tf/shape), [`tf.where`](https://www.tensorflow.org/api_docs/python/tf/where), [`tf.tensor_scatter_nd_update`](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update), [`tf.math.logical_and`](https://www.tensorflow.org/api_docs/python/tf/math/logical_and)

In [23]:
def zad3(T1,T2)->tf.Tensor:
    assert all(tf.shape(T1) == tf.shape(T2))
    assert T1.dtype == tf.float32
    assert T2.dtype == tf.float32
    id1 = 0 < T1
    id2 =  T1 < 4
    id = tf.where(tf.math.logical_and(id1,id2))
    updates = tf.constant([7], shape=[tf.shape(id)[0]], dtype=tf.float32)
    return tf.tensor_scatter_nd_update(T2,id,updates)

T1=tf.constant([[8, 9, 0], [2, 3, 4], [6, 1, 8]],dtype=tf.float32)
T2=tf.constant([[4, 5, 8], [23, 32, 14], [6, 1, 15]],dtype=tf.float32)
print(zad3(T1,T2))
T1=tf.constant([[8, 9], [3, 4], [6, 2]],dtype=tf.float32)
T2=tf.constant([[5, 8], [23, 14], [6, 1]],dtype=tf.float32)
print(zad3(T1,T2))

tf.Tensor(
[[ 4.  5.  8.]
 [ 7.  7. 14.]
 [ 6.  7. 15.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 5.  8.]
 [ 7. 14.]
 [ 6.  7.]], shape=(3, 2), dtype=float32)
